[package]
name = "steno-phonetics"
version = "0.1.0"
edition = "2021"

[dependencies]
enumset = "1.1.5"
reqwest = { version = "0.12.12", features = ["blocking", "json"] }
serde = { version = "1.0.217", features = ["derive"] }
trie-rs = "0.4.2"
